pipeline:
  build:
    image: node:16-alpine
    commands:
      - yarn i
      - yarn build
    when:
      event: tag
  test:
    image: node:16-alpine
    commands:
      - yarn test
    when:
      event: tag
  release:
    image: node:16-alpine
    commands:
      - yarn ci
    secrets: [ GH_TOKEN ]
    when:
      event: tag
  publish:
    image: plugins/docker
    secrets: [ docker_registery ]
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_mirana_uri
      dockerfile: dockerfile/Dockerfile
      tags: "${CI_COMMIT_TAG}"
      build_args_from_env:
        - REGISTERY
    when:
      event: tag
      tag: v.mirana*
branches: [ "*alpha*" ]