pipeline:
  build:
    image: node:16-alpine
    commands:
      - yarn install --frozen-lockfile --ignore-scripts
      - yarn build
  test:
    image: node:16-alpine
    commands:
      - yarn test
  release:
    image: node:16-alpine
    commands:
      - apk add git
      - yarn ci
    secrets: [ GH_TOKEN ]
  publish:
    image: plugins/docker
    secrets: [ docker_registery ]
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_mirana_uri
      dockerfile: dockerfile/Dockerfile
      tags: "${CI_COMMIT_TAG}"
      build_args_from_env:
        - REGISTERY
    when:
      event: tag
      tag: v.mirana*
branches: [ master, Mirana ]